dist: trusty
sudo: required
language: bash
before_install: curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh
  | bash
notifications:
  slack:
    rooms:
      secure: 2k6nsK/VEFQ4sGnoYerffd2q+JgJfIbtFQ2HMeaqSyQ8ZJ7I+TCyfNAKYIl4I4rJxBnYnKyhFH7CdhbLjo4h4tfgL2UxA7e2eEXWLdV8yDUmGcvdIDwHu13SQRewp7MpAdkyjaVkUF+JKdXEco7F9C8SxzMCvFMcARkRzvBRTXfHpdvMMvjmQjbsg09uE6e1JYU9bG7Dc+GwiNKnhhXsotIM67spIGen8oZJ8J2ygGRtBZY1v0b1Z/1Xi53ybSfmsEStlIX5WDlGS2y5yJw63HqbRFAdEFXNwtgTcVePeHC5CEGyQwfr765pmxMglnM5QRZ6UkFab2iI+Zr4WeV6inlkuPDmMUiJZ7WVBKKPenXkDybShVxEtERls7d7JylGwz8ERFD6wvxb0Fqd3WjIGdRFeVeyPuhQ+Nd0QQHOF8dkL4zuIy9ZTVVcQpSAELeigxB69pL0GcB3mGolJH63dZmE9oPK5sX8d/gfBLaE7JS6wmnvWNt+mjXgI2PGvBgYXj17ngFjFxIG/N3LClWGjz+0t/r8a/sg7pMWMlVxfVLbDky5Y1cQhSA3PMwhhbDwcQt1HlBTgIl6WZazNoCOgnol1rtXAfR9FwITnw72ga57pjMnsR40HqcheMR910c5h1cM6np6CGFVRkXguI45OgJFAhOqNxpj3C93XKUy2Ac=
