$ANSIBLE_VAULT;1.1;AES256
62303930323031326130616634646564666230386430336564373237363064643365326138363562
3664336661356431363362633566363439393133363764350a393433313263656533363666613036
32653964313434323638323036636261643063306332666238383232653933616566323162333133
3630626631626337620a663561353839326361343465643935336531316165386138303865333732
61656136383738336439653336623937393862393133646262353331366631313366396135363831
65333764333433643336613732373762353162333238393635643239353766336465356365396464
62353238376134373230383830626638643530363766626463636464343963326535376332383232
65313834396633316532643261303233666337386135636663343563346436646336613032666464
35663266346435313966666237646438653336663033383666346436396364386563353235383237
6632323163353862393561633438653361336336373561633639
